[0.0.5 fixes]

diff --git a/application/tmp/webister/files/service b/application/tmp/webister/files/service
--- a/application/tmp/webister/files/service
+++ b/application/tmp/webister/files/service
@@ -9,7 +9,7 @@
 #bash_version    :4.1.5(1)-release
 #==============================================================================
 if [[ $EUID -ne 0 ]]; then
-   echo "This script must be run as root! Please contact Tecflare, if you are experiencing errors." 1>&2
+   echo "This script must be run as root! Please contact Adaclare, if you are experiencing errors." 1>&2
    exit 1
 fi
 case "$1" in
@@ -19,6 +19,7 @@ case "$1" in
     echo -n $"Starting webister daemon: "
 
     echo
+    su webister -c "cd /var/webister/80 && sudo php -S 0.0.0.0:8080 &>/dev/null &"
     su webister -c "cd /var/webister/interface && sudo php -S 0.0.0.0:8081 &>/dev/null &"
     #development purpose only
     #su webister -c "cd /home/ubuntu/workspace/interface && sudo php -S 0.0.0.0:8081 &>/dev/null &"
